#!/usr/bin/env python3
"""Validate public Agent Skills in this repository.

This script deliberately uses only the Python standard library so contributors can
run it without project setup.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = ROOT / "skills"
PUBLIC_TEXT_ROOTS = [
    ROOT / "README.md",
    ROOT / "CONTRIBUTING.md",
    ROOT / "agent-support.json",
    ROOT / "docs",
    ROOT / "skills",
    ROOT / "examples",
]
EXPECTED_AUTHOR = "Sergiu Vataman (Nylas)"
EXPECTED_LICENSE = "MIT"
EXPECTED_HOMEPAGE = "https://github.com/NylasDev/nylas-dungeon-master-skills"
MAX_DESCRIPTION_LENGTH = 1024
WARN_DESCRIPTION_LENGTH = 160
MAX_SKILL_CHARS = 100_000
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SUPPORT_PATH_RE = re.compile(r"(?<![\w/])((?:references|templates|scripts|assets)/[A-Za-z0-9_.\-/]+\.[A-Za-z0-9]+)")

ATTRIBUTION_PATTERNS = [
    r"co-authored-by",
    r"helped by",
    r"contributed by",
    r"generated by",
    r"generated with",
    r"created by chatgpt",
    r"created with chatgpt",
    r"created by ai",
    r"created with ai",
    r"assistant credit",
]

PROPRIETARY_MARKERS = [
    r"Player'?s Handbook",
    r"Dungeon Master'?s Guide",
    r"Monster Manual",
    r"Forgotten Realms",
    r"Waterdeep",
    r"Strahd",
    r"Baldur",
]


def iter_text_files(root: Path):
    if root.is_file():
        yield root
        return
    if not root.exists():
        return
    for path in root.rglob("*"):
        if ".git" in path.parts:
            continue
        if path.is_file() and path.suffix.lower() in {".md", ".txt", ".yml", ".yaml", ".py", ".json", ".jsonc", ".sh"}:
            yield path


def parse_simple_frontmatter(text: str, path: Path, errors: list[str]) -> tuple[dict[str, str], str]:
    if not text.startswith("---"):
        errors.append(f"{path}: SKILL.md must start with --- at byte 0")
        return {}, text

    marker = "\n---\n"
    close = text.find(marker, 3)
    if close == -1:
        errors.append(f"{path}: frontmatter must close with a line containing ---")
        return {}, ""

    raw = text[3:close]
    body = text[close + len(marker):]
    data: dict[str, str] = {}

    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith(" ") or line.startswith("-"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        data[key] = value

    return data, body


def validate_skill(path: Path, errors: list[str], warnings: list[str]) -> None:
    rel = path.relative_to(ROOT)
    text = path.read_text(encoding="utf-8")
    data, body = parse_simple_frontmatter(text, rel, errors)

    if len(text) > MAX_SKILL_CHARS:
        errors.append(f"{rel}: file is {len(text)} chars, over {MAX_SKILL_CHARS}")

    name = data.get("name", "")
    description = data.get("description", "")
    author = data.get("author", "")
    license_name = data.get("license", "")
    homepage = data.get("homepage", "")
    user_invocable = data.get("user-invocable", "")

    if not name:
        errors.append(f"{rel}: missing name in frontmatter")
    elif name != path.parent.name:
        errors.append(f"{rel}: name '{name}' must match parent directory '{path.parent.name}'")
    elif not NAME_RE.match(name):
        errors.append(f"{rel}: name '{name}' must use lowercase letters, numbers, and single hyphens")

    if not description:
        errors.append(f"{rel}: missing description in frontmatter")
    elif len(description) > MAX_DESCRIPTION_LENGTH:
        errors.append(f"{rel}: description is {len(description)} chars, over {MAX_DESCRIPTION_LENGTH}")
    elif len(description) > WARN_DESCRIPTION_LENGTH:
        warnings.append(f"{rel}: description is {len(description)} chars; consider keeping discovery text under {WARN_DESCRIPTION_LENGTH}")

    if author != EXPECTED_AUTHOR:
        errors.append(f"{rel}: author should be '{EXPECTED_AUTHOR}'")

    if license_name != EXPECTED_LICENSE:
        errors.append(f"{rel}: license should be '{EXPECTED_LICENSE}'")

    if homepage != EXPECTED_HOMEPAGE:
        errors.append(f"{rel}: homepage should be '{EXPECTED_HOMEPAGE}' for public agent directory compatibility")

    if user_invocable.lower() != "true":
        errors.append(f"{rel}: user-invocable should be true for OpenClaw slash-command discovery")

    for required_block in ("  hermes:", "  agentskills:", "  openclaw:"):
        if required_block not in text:
            errors.append(f"{rel}: metadata block missing {required_block.strip()}")

    if "    always: true" not in text:
        errors.append(f"{rel}: metadata.openclaw.always should be true because these skills require no external tools")

    if not body.strip():
        errors.append(f"{rel}: body is empty")

    for match in SUPPORT_PATH_RE.finditer(text):
        support_rel = match.group(1)
        support_path = path.parent / support_rel
        if not support_path.exists():
            errors.append(f"{rel}: referenced support file does not exist: {support_rel}")


def scan_public_text(errors: list[str], warnings: list[str]) -> None:
    seen: set[Path] = set()
    for root in PUBLIC_TEXT_ROOTS:
        for path in iter_text_files(root):
            if path in seen:
                continue
            seen.add(path)
            text = path.read_text(encoding="utf-8", errors="replace")
            rel = path.relative_to(ROOT)

            in_fenced_code = False
            for line_no, line in enumerate(text.splitlines(), start=1):
                if line.strip().startswith("```"):
                    in_fenced_code = not in_fenced_code
                    continue
                if in_fenced_code:
                    continue

                for pattern in ATTRIBUTION_PATTERNS:
                    if re.search(pattern, line, flags=re.IGNORECASE):
                        errors.append(f"{rel}:{line_no}: possible unwanted assistant/coauthor attribution phrase: {pattern}")

                for pattern in PROPRIETARY_MARKERS:
                    if re.search(pattern, line, flags=re.IGNORECASE):
                        warnings.append(f"{rel}:{line_no}: proprietary/sourcebook marker found; ensure this is only hygiene discussion: {pattern}")


def validate_agent_support(skill_names: set[str], errors: list[str]) -> None:
    support_path = ROOT / "agent-support.json"
    if not support_path.exists():
        errors.append("agent-support.json is missing")
        return

    try:
        data = json.loads(support_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        errors.append(f"agent-support.json: invalid JSON: {exc}")
        return

    if data.get("repository") != "NylasDev/nylas-dungeon-master-skills":
        errors.append("agent-support.json: repository must be NylasDev/nylas-dungeon-master-skills")

    support_skills = {entry.get("name") for entry in data.get("skills", [])}
    if support_skills != skill_names:
        errors.append(f"agent-support.json: skills {sorted(support_skills)} do not match SKILL.md files {sorted(skill_names)}")

    for entry in data.get("skills", []):
        name = entry.get("name")
        path_value = entry.get("path")
        if not name or not path_value:
            errors.append("agent-support.json: each skill entry needs name and path")
            continue
        if not (ROOT / path_value / "SKILL.md").exists():
            errors.append(f"agent-support.json: skill path missing SKILL.md for {name}: {path_value}")

    first_class = {entry.get("id") for entry in data.get("first_class_agents", [])}
    for required in ("hermes-agent", "openclaw"):
        if required not in first_class:
            errors.append(f"agent-support.json: missing first-class agent {required}")

    cli_agents = [entry.get("id") for entry in data.get("skills_cli_agents", [])]
    if len(cli_agents) != len(set(cli_agents)):
        errors.append("agent-support.json: duplicate skills_cli_agents ids found")

    for required in ("claude-code", "codex", "opencode", "cursor", "github-copilot"):
        if required not in cli_agents:
            errors.append(f"agent-support.json: missing common Skills CLI agent {required}")

    validation = data.get("validation", [])
    if "bash scripts/smoke-agent-installs.sh" not in validation:
        errors.append("agent-support.json: validation should include bash scripts/smoke-agent-installs.sh")


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    skill_files = sorted(SKILLS_ROOT.rglob("SKILL.md")) if SKILLS_ROOT.exists() else []
    if not skill_files:
        errors.append("No SKILL.md files found under skills/")

    for path in skill_files:
        validate_skill(path, errors, warnings)

    skill_names = {path.parent.name for path in skill_files}
    validate_agent_support(skill_names, errors)

    scan_public_text(errors, warnings)
    print(f"Validated {len(skill_files)} skill file(s).")

    if warnings:
        print("\nWarnings:")
        for warning in warnings:
            print(f"  - {warning}")

    if errors:
        print("\nErrors:")
        for error in errors:
            print(f"  - {error}")
        return 1

    print("No validation errors.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
